/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 neusa_frois.glb --transform
Author: SrMonteiro (https://sketchfab.com/crispimrafael)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/neusa-frois-916185bb2d4c48829591ba95958b9dcd
Title: Neusa Frois
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useBox } from '@react-three/cannon'

export function Model(props) {
  const { nodes, materials } = useGLTF('/neusa_frois-transformed.glb')
  const [ref] = useBox(() => ({
    mass: 0,
    position: props.position,
    scale: [0.03, 0.03, 0.03], // Adjust scale to match your model
  }))
  return (
    <group {...props} dispose={null}>
      <group scale={0.03}>
        <group position={[93.5, 45.28, -78.74]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['SlidingDoor001_Material_#2146801343_0'].geometry} material={materials.Material_2146801343} />
          <mesh geometry={nodes['SlidingDoor001_Material_#2146801355_0'].geometry} material={materials.Material_2146801355} />
        </group>
        <group position={[93.5, 64.96, 227.54]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['SlidingWindow002_Material_#2146801343_0'].geometry} material={materials.Material_2146801343} />
          <mesh geometry={nodes['SlidingWindow002_Material_#2146801355_0'].geometry} material={materials.Material_2146801355} />
        </group>
        <group position={[93.5, 64.96, 11.81]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['SlidingWindow003_Material_#2146801343_0'].geometry} material={materials.Material_2146801343} />
          <mesh geometry={nodes['SlidingWindow003_Material_#2146801355_0'].geometry} material={materials.Material_2146801355} />
        </group>
        <group position={[18.7, 64.96, -270.67]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['SlidingWindow004_Material_#2146801343_0'].geometry} material={materials.Material_2146801343} />
          <mesh geometry={nodes['SlidingWindow004_Material_#2146801355_0'].geometry} material={materials.Material_2146801355} />
        </group>
        <group position={[-78.82, 77.11, 83.29]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_011_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-78.87, 77.11, 74.02]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_012_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-77.62, 77.11, 91.63]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_013_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-78.28, 77.11, 42.01]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_014_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-79.34, 77.11, 34.05]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_015_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-78.7, 77.11, 51.49]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_016_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-79.22, 62.96, 82.71]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_017_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-78.21, 62.96, 73.62]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_018_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-79.1, 62.96, 91.7]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_019_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-78.28, 62.96, 42.13]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_020_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-78.22, 62.96, 34.27]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_021_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-78.8, 62.96, 50.44]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_022_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-77.3, 48.81, 82.27]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_023_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-78.51, 48.81, 74.06]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_024_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-78.79, 48.81, 92.12]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_025_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-78.26, 48.81, 42.41]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_026_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-78.36, 48.81, 33.59]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_027_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-80.19, 48.81, 51.68]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_028_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-79.26, 34.67, 82.12]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_029_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-77.43, 34.67, 73.75]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_030_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-77.93, 34.67, 91.2]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_031_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-79.49, 34.67, 42.56]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_032_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-78.35, 34.67, 32.67]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_033_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-79.2, 34.67, 51.54]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_034_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-78.96, 20.52, 83.16]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_035_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-79.11, 20.52, 73.6]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_036_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-78.96, 20.52, 91.3]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_037_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-78.89, 20.52, 42.73]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_038_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-79.44, 20.52, 32.89]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_039_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-79.1, 20.52, 50.32]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_040_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-78.48, 6.91, 80.42]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_041_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-78.47, 6.91, 72.23]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_042_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-78.28, 6.91, 88.54]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_043_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-81.4, 6.91, 38.62]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_044_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-80.42, 6.91, 30.7]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_045_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <group position={[-81.04, 6.91, 47.36]} rotation={[-1.57, 0, 2.92]} scale={0.07}>
          <mesh geometry={nodes['5#1_046_Material_#3524_0'].geometry} material={materials.Material_3524} position={[-67.49, -440.98, -82.13]} />
        </group>
        <mesh geometry={nodes['Line001_Material_#2143567293_0'].geometry} material={materials.Material_2143567293} position={[-22.64, 60.04, 0]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Group_051_Material_#64_0'].geometry} material={materials.Material_64} position={[17.57, 42.36, -260.56]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Obj3d66-707242-3-267__0'].geometry} material={materials['Obj3d66-707242-3-267__0']} position={[17.29, 14.98, 255.76]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Obj3d66-707242-32-41_Mat3d66-707242-13-5970_0'].geometry} material={materials['Mat3d66-707242-13-5970']} position={[69.08, 33.51, 117.55]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Obj3d66-707242-34-401__0'].geometry} material={materials['Obj3d66-707242-3-267__0']} position={[69.06, 52.3, 117.6]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Obj3d66-707242-36-470__0'].geometry} material={materials['Obj3d66-707242-3-267__0']} position={[69.07, 45.51, 117.61]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Obj3d66-707242-38-435__0'].geometry} material={materials['Obj3d66-707242-3-267__0']} position={[69.07, 58.83, 117.61]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Object280_Material_#2143566212_0'].geometry} material={materials.Material_2143566212} position={[-22.35, 118.19, 23.53]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['_72_Material_#2143567290_0'].geometry} material={materials.Material_2143567290} position={[73.9, 35.53, -196.7]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box076_Material_#2143567292_0'].geometry} material={materials.Material_2143567292} position={[-29.12, 60.04, 53.95]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Obj3d66-707242-43-731_Material_#2143567294_0'].geometry} material={materials.Material_2143567294} position={[-27.29, 58.95, 23.69]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box065_Material_#2143567291_0'].geometry} material={materials.Material_2143567291} position={[87.64, 60.16, 75.04]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['_313_Material_#2146801357_0'].geometry} material={materials.Material_2146801357} position={[42.43, 44.35, 266.48]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[1.25, 1, 1.25]} />
        <mesh geometry={nodes['Box077_Material_#2146801360_0'].geometry} material={materials.Material_2146801360} position={[-81.69, 0, 61.12]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object284__0.geometry} material={materials['Obj3d66-707242-3-267__0']} position={[-43.7, 0, -60.63]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Object285_Material_#2146801358_0'].geometry} material={materials.Material_2146801358} position={[42.43, 44.35, 266.48]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[1.25, 1, 1.25]} />
        <mesh geometry={nodes['Object286_Material_#2146801359_0'].geometry} material={materials.Material_2146801359} position={[42.43, 44.35, 266.48]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[1.25, 1, 1.25]} />
        <mesh geometry={nodes['Box078_Material_#2146801356_0'].geometry} material={materials.Material_2146801356} position={[-73.01, 1.97, 61.12]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Object287_Material_#2146801361_0'].geometry} material={materials.Material_2146801361} position={[-27.29, 58.95, 23.69]} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/neusa_frois-transformed.glb')
